name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./beyond
      - run: flutter test
        working-directory: ./beyond
      - run: flutter pub get
        working-directory: ./beyond_helpers
      - run: flutter test
        working-directory: ./beyond_helpers

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./beyond
      - run: flutter analyze
        working-directory: ./beyond
      - run: flutter pub get
        working-directory: ./beyond_helpers
      - run: flutter analyze
        working-directory: ./beyond_helpers